spring:
  data:
    mongodb:
      uri: mongodb://127.0.0.1:27017/websocket_study
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/websocket_study?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 1234

  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        #format_sql: true
      dialect: org.hibernate.dialect.MySQL8InnoDBDialect

springdoc:
  swagger-ui:
    operations-sorter: method
    path: /
    groups-order: desc
    disable-swagger-default-url: true
    display-request-duration: true

  api-docs:
    groups:
      enabled: true